export const countries = [
  { code: 'TN', name: 'Tunisie', dialCode: '+216' },
  { code: 'DZ', name: 'Algerie', dialCode: '+213' },
  { code: 'MA', name: 'Maroc', dialCode: '+212' },
  { code: 'LY', name: 'Libye', dialCode: '+218' },
  { code: 'EG', name: 'Egypte', dialCode: '+20' },
  { code: 'MR', name: 'Mauritanie', dialCode: '+222' },
  { code: 'SA', name: 'Arabie saoudite', dialCode: '+966' },
  { code: 'AE', name: 'Emirats arabes unis', dialCode: '+971' },
  { code: 'QA', name: 'Qatar', dialCode: '+974' },
  { code: 'KW', name: 'Koweit', dialCode: '+965' },
  { code: 'BH', name: 'Bahrein', dialCode: '+973' },
  { code: 'OM', name: 'Oman', dialCode: '+968' },
  { code: 'JO', name: 'Jordanie', dialCode: '+962' },
  { code: 'LB', name: 'Liban', dialCode: '+961' },
  { code: 'TR', name: 'Turquie', dialCode: '+90' },
  { code: 'FR', name: 'France', dialCode: '+33' },
  { code: 'BE', name: 'Belgique', dialCode: '+32' },
  { code: 'DE', name: 'Allemagne', dialCode: '+49' },
  { code: 'GB', name: 'Royaume-Uni', dialCode: '+44' },
  { code: 'IT', name: 'Italie', dialCode: '+39' },
  { code: 'ES', name: 'Espagne', dialCode: '+34' },
  { code: 'US', name: 'Etats-Unis', dialCode: '+1' },
  { code: 'CA', name: 'Canada', dialCode: '+1' },
  { code: 'SN', name: 'Senegal', dialCode: '+221' },
  { code: 'ML', name: 'Mali', dialCode: '+223' },
  { code: 'NE', name: 'Niger', dialCode: '+227' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234' },
  { code: 'SD', name: 'Soudan', dialCode: '+249' },
  { code: 'PK', name: 'Pakistan', dialCode: '+92' },
  { code: 'IN', name: 'Inde', dialCode: '+91' },
  { code: 'ID', name: 'Indonesie', dialCode: '+62' },
  { code: 'MY', name: 'Malaisie', dialCode: '+60' },
]

export const countryNames = countries.map((country) => country.name)
