// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB84L-M0zKDRcidLmSeZmoZBe3zrTw8dMg',
    appId: '1:1029812656960:web:ccb02c72cd72624f96f8a5',
    messagingSenderId: '1029812656960',
    projectId: 'pilgrimage-pfe-25472',
    authDomain: 'pilgrimage-pfe-25472.firebaseapp.com',
    storageBucket: 'pilgrimage-pfe-25472.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFf9bW_ie-Vw7zaYrpHJaN7N9F0BO2e3U',
    appId: '1:1029812656960:android:b950bf7868f0e15496f8a5',
    messagingSenderId: '1029812656960',
    projectId: 'pilgrimage-pfe-25472',
    storageBucket: 'pilgrimage-pfe-25472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcX0vY5U_LYkagPMMAnwi2B9B1k6l-egY',
    appId: '1:1029812656960:ios:b79681223a1a5b6896f8a5',
    messagingSenderId: '1029812656960',
    projectId: 'pilgrimage-pfe-25472',
    storageBucket: 'pilgrimage-pfe-25472.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcX0vY5U_LYkagPMMAnwi2B9B1k6l-egY',
    appId: '1:1029812656960:ios:b79681223a1a5b6896f8a5',
    messagingSenderId: '1029812656960',
    projectId: 'pilgrimage-pfe-25472',
    storageBucket: 'pilgrimage-pfe-25472.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB84L-M0zKDRcidLmSeZmoZBe3zrTw8dMg',
    appId: '1:1029812656960:web:ddb449a91b7675b796f8a5',
    messagingSenderId: '1029812656960',
    projectId: 'pilgrimage-pfe-25472',
    authDomain: 'pilgrimage-pfe-25472.firebaseapp.com',
    storageBucket: 'pilgrimage-pfe-25472.firebasestorage.app',
  );
}
